import { StyleSheet } from "react-native";
import { palette, radius } from "./theme";

export const s = StyleSheet.create({
  screen: { flex: 1, padding: 18, gap: 14 },
  h1: { color: palette.ink, fontSize: 26, fontWeight: "700" },
  lead: { color: palette.inkDim, fontSize: 15, lineHeight: 22 },
  card: {
    backgroundColor: palette.cardFill,
    borderColor: palette.cardBorder,
    borderWidth: 1,
    borderRadius: radius,
    padding: 18,
    gap: 6,
  },
  cardTitle: { color: palette.ink, fontSize: 18, fontWeight: "700" },
  cardBody: { color: palette.inkDim, fontSize: 14, lineHeight: 21 },
  btn: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.cardBorder,
    backgroundColor: "rgba(255,255,255,0.06)",
    paddingVertical: 16,
    paddingHorizontal: 18,
    alignItems: "center",
  },
  btnText: { color: palette.ink, fontSize: 16, fontWeight: "600" },
  btnPrimary: { backgroundColor: palette.accent, borderColor: "transparent" },
  btnPrimaryText: { color: "#2a0a10", fontSize: 16, fontWeight: "700" },
  btnDanger: { backgroundColor: palette.danger, borderColor: "transparent" },
  btnDisabled: { opacity: 0.45 },
  choice: { alignItems: "flex-start" },
  pill: {
    alignSelf: "flex-start",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: palette.cardBorder,
    paddingVertical: 5,
    paddingHorizontal: 11,
  },
  pillText: { color: palette.inkDim, fontSize: 12, fontWeight: "600" },
  topbar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingTop: 8,
    paddingBottom: 10,
  },
  brand: { flexDirection: "row", alignItems: "center", gap: 8 },
  brandDot: {
    width: 11,
    height: 11,
    borderRadius: 6,
    backgroundColor: palette.accent,
  },
  brandText: { color: palette.ink, fontSize: 17, fontWeight: "700" },
  tabbar: {
    flexDirection: "row",
    justifyContent: "space-around",
    borderTopWidth: 1,
    borderTopColor: palette.cardBorder,
    backgroundColor: "rgba(20,6,10,0.85)",
    paddingTop: 10,
    paddingBottom: 24,
  },
  tab: { alignItems: "center", gap: 3 },
  tabLabel: { color: palette.inkFaint, fontSize: 11, fontWeight: "600" },
  tabLabelActive: { color: palette.accent },
  tabIcon: { fontSize: 18 },
  center: { flex: 1, alignItems: "center", justifyContent: "center", gap: 16 },
  moodRow: { flexDirection: "row", gap: 8 },
  mood: {
    flex: 1,
    aspectRatio: 1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.cardBorder,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  moodSelected: { backgroundColor: palette.accentSoft, borderColor: palette.accent },
  moodEmoji: { fontSize: 26 },
  barTrack: {
    height: 9,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.08)",
    overflow: "hidden",
  },
  barFill: { height: 9, borderRadius: 999, backgroundColor: palette.accent },
  disclaimer: {
    color: palette.inkFaint,
    fontSize: 12,
    textAlign: "center",
    lineHeight: 18,
  },
  metricHead: { flexDirection: "row", justifyContent: "space-between" },
});
