import type { DailyPoint, Disposition } from "./types";
import type { TriageState, TriageStep } from "./triage";
import {
  metricBlinkRate,
  metricHnr,
  metricMood,
  metricWellbeing,
  trend,
  type TrendSummary,
} from "./trends";

export interface HandoffMetricTrend {
  metric: string;
  direction: TrendSummary["direction"];
  latest: number | undefined;
  baselineMean: number;
  readings: number;
}

/**
 * A structured GP-handoff summary, built deterministically from the user's
 * own data. An LLM may later phrase `narrativeDraft` into prose, but every
 * field here is computed, not invented, so the clinical content is auditable.
 */
export interface HandoffSummary {
  generatedAt: number;
  windowDays: number;
  checkInCount: number;
  presentingTopics: string[];
  redFlagsRaised: string[];
  triageAnswers: Array<{ question: string; answer: string; topic?: string }>;
  disposition: {
    level: Disposition["level"];
    title: string;
    reason?: string;
  } | null;
  trends: HandoffMetricTrend[];
  narrativeDraft: string;
  disclaimer: string;
}

const DISCLAIMER =
  "Generated by An Apple a Day from the patient's own check-ins. This is a wellbeing log and signposting summary, not a diagnosis or a medical device. Care decisions were made by the patient using NHS signposting.";

function uniqueTopics(steps: TriageStep[]): string[] {
  const seen = new Set<string>();
  for (const s of steps) if (s.topic) seen.add(s.topic);
  return [...seen];
}

function daysBetween(points: DailyPoint[]): number {
  if (points.length < 2) return points.length === 1 ? 1 : 0;
  const ts = points.map((p) => p.timestamp).sort((a, b) => a - b);
  const first = ts[0] as number;
  const last = ts[ts.length - 1] as number;
  return Math.max(1, Math.round((last - first) / (24 * 60 * 60 * 1000)));
}

export function buildHandoff(
  points: DailyPoint[],
  triage: TriageState | null,
  now: number,
): HandoffSummary {
  const steps = triage?.history ?? [];
  const topics = uniqueTopics(steps);
  // For instrument-driven escalations the node prompt is generic ("a few quick
  // questions..."), so surface the specific disposition reason instead.
  const redFlags = steps
    .filter((s) => s.redFlag)
    .map((s) =>
      s.answer.endsWith("completed") && triage?.disposition?.reason
        ? triage.disposition.reason
        : s.prompt,
    );

  const trends: HandoffMetricTrend[] = [
    { metric: "Wellbeing index", extractor: metricWellbeing, better: true },
    { metric: "Self-reported mood", extractor: metricMood, better: true },
    { metric: "Voice clarity (HNR)", extractor: metricHnr, better: true },
    { metric: "Blink rate", extractor: metricBlinkRate, better: true },
  ].map(({ metric, extractor, better }) => {
    const t = trend(points, extractor, { higherIsBetter: better });
    return {
      metric,
      direction: t.direction,
      latest: t.latest,
      baselineMean: Number(t.baseline.mean.toFixed(2)),
      readings: t.baseline.n,
    };
  });

  const disposition = triage?.disposition ?? null;

  return {
    generatedAt: now,
    windowDays: daysBetween(points),
    checkInCount: points.length,
    presentingTopics: topics,
    redFlagsRaised: redFlags,
    triageAnswers: steps
      .filter((s) => s.answer)
      .map((s) => ({ question: s.prompt, answer: s.answer, topic: s.topic })),
    disposition: disposition
      ? {
          level: disposition.level,
          title: disposition.title,
          reason: disposition.reason,
        }
      : null,
    trends,
    narrativeDraft: draftNarrative(points, topics, redFlags, disposition, trends),
    disclaimer: DISCLAIMER,
  };
}

function draftNarrative(
  points: DailyPoint[],
  topics: string[],
  redFlags: string[],
  disposition: Disposition | null,
  trends: HandoffMetricTrend[],
): string {
  const parts: string[] = [];
  parts.push(
    `Patient completed ${points.length} self check-in${points.length === 1 ? "" : "s"} over the period.`,
  );
  if (topics.length) {
    parts.push(`Concerns raised: ${topics.join(", ")}.`);
  }
  if (redFlags.length) {
    if (disposition?.level === "emergency-999") {
      parts.push(
        "Emergency warning signs were flagged and the patient was advised to call 999.",
      );
    } else if (disposition?.level === "urgent-111") {
      parts.push(
        "Some answers needed urgent advice and the patient was directed to NHS 111.",
      );
    } else {
      parts.push("Warning signs were noted during the check-in.");
    }
  }
  const worsening = trends.filter((t) => t.direction === "worsening");
  if (worsening.length) {
    parts.push(
      `Trending worse against the patient's own baseline: ${worsening
        .map((t) => t.metric.toLowerCase())
        .join(", ")}.`,
    );
  }
  if (disposition) {
    parts.push(`Most recent signposting outcome: ${disposition.title}.`);
  }
  return parts.join(" ");
}

export { DISCLAIMER };
